### ISSUE TITLE
I get the error 'NoneType' object has no attribute 'lower' when running

### ISSUE THREAD

**Issue by lezyamin** [MatteoFasulo/Whisper-TikTok#9]
I am using the command: 
python main.py --model medium --tts en-US-EricNeural
 
And am getting the following error: 
`AttributeError: 'NoneType' object has no attribute 'lower'           | ERROR | 'NoneType' object has no attribute 'lower'      main.py:551`

Looking in my logs I can see:

`2023-12-21 11:31:37,884 - __main__ - ERROR - 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/home/rdpuser/Downloads/whisper/main.py", line 547, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/rdpuser/Downloads/whisper/main.py", line 209, in main
    highlight_words(srt_filename, subtitle_format=args.sub_format,
  File "/home/rdpuser/Downloads/whisper/main.py", line 431, in highlight_words
    subtitle_format = subtitle_format.lower()
AttributeError: 'NoneType' object has no attribute 'lower'`

Hope this helps. Let me know if I can provide anymore logs!

**Comment by lezyamin** [comment]
I thought my python version may have been an issue, but have updated to 3.11 and still get:

`2023-12-21 12:40:00,571 - __main__ - INFO - Finish loading environment variables
2023-12-21 12:40:00,572 - __main__ - WARNING - PyTorch GPU not found
2023-12-21 12:42:07,314 - __main__ - INFO - Background video downloaded successfully
2023-12-21 12:42:42,524 - __main__ - INFO - OpenAI-Whisper model loaded successfully (medium.en)
2023-12-21 12:42:42,526 - __main__ - INFO - Text converted successfully
2023-12-21 12:42:44,568 - __main__ - INFO - Text2Speech mp3 file generated successfully with voice en-US-EricNeural
2023-12-21 12:43:11,244 - __main__ - INFO - Transcription srt file saved successfully!
2023-12-21 12:43:11,247 - __main__ - ERROR - 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/home/rdpuser/Downloads/aivid/main.py", line 547, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/rdpuser/Downloads/aivid/main.py", line 209, in main
    highlight_words(srt_filename, subtitle_format=args.sub_format,
  File "/home/rdpuser/Downloads/aivid/main.py", line 431, in highlight_words
    subtitle_format = subtitle_format.lower()
                      ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'`

**Comment by MatteoFasulo** [comment]
Hi @lezyamin were you able to solve the issue? If so, what was the cause?
